### ISSUE TITLE
the trait `Clone` is not implemented for `Ctr128LE`

### ISSUE THREAD

**Issue by jimouris** [RustCrypto/block-modes#23]
Hi, pretty much whatever the title says _the trait `Clone` is not implemented for `Ctr128LE`_. I'm trying to create a struct:

```
#[derive(Clone)]
pub struct PrgStream {
    stream: Aes128Ctr128LE,
}
```
and `Clone` is not supported.

**Comment by newpavlov** [comment]
Yeah, deriving `Clone` on `CtrCore` results in a redundant `Clone` bound on used flavor. Direct implementation without the bound should fix it.

**Comment by jimouris** [comment]
Thanks!
