### ISSUE TITLE
How should I use AES-256-CBC to decrypt?

### ISSUE THREAD

**Issue by baby195lxl** [RustCrypto/block-modes#37]
I am trying to decrypt a string using AES-256-CBC, but I am getting an error message 'thread 'main' panicked at 'called Result::unwrap() on an Err value: UnpadError'. Did I miss any steps?
```rust
use base64::{Engine as _, alphabet, engine::{GeneralPurposeConfig, self}};
use aes::cipher::{block_padding::Pkcs7, BlockDecryptMut, KeyIvInit};

type Aes256CbcDec = cbc::Decryptor<aes::Aes256>;

fn main() {
    let config = GeneralPurposeConfig::new().with_decode_allow_trailing_bits(true);
    let s = String::from("no7AfO7XatdfEGhh1bLIU5wT4U5X2712vyWJbmQAbyK=");
    println!("{}", s);

    let key = engine::GeneralPurpose::new(&alphabet::STANDARD, config).decode(s).unwrap();
    let key_output: [u8; 32] = key.clone().try_into().unwrap();
    println!("{:?}", key_output.len());

    let iv = &key[..16];
    let iv_output: [u8; 16] = iv.try_into().unwrap();
    println!("{:?}", iv_output.len());

    let encrypt = "yWgEEgiU97Bd/cX4ezT+Rk/78oJbABb9gr/N73FbBCvgPd3po2JyHYMsSmiyNgEXI+6f2kXxqBdxm/bfTs909UhYvW2PzXzMx4FiDiEAmnogBHNtw7W3kjUZVCDfuU3V1eRRM+QEI+rRXlgMcSKlaLXuEOIKn+AQuD53yXPsXzMdbb+5/Zs8zXddJjN1AtOmI0D8ZJOW6yBjJARk4dFn62Ks/SZai5ec9zg13LZOx8dt1DeI5eF/gqpJZorn5nGhWEX3pR3/XDTwn7u1hdbUeu7Eyu/mmmUQiwlWjVLxIOONHQQRuOSWfy+OePcbvsQSPt4E4Ec6THrW+y5WcWKIEEFSh/GFwC+7ueElNLNErAha6mflewBivoXplC4PRLGB/1uHfV1O1gBxPBtzH2x8X8NlFWptjjGjUSb4jzBj07hmdhPul7bNw0tha7FVibQCUKWqOmiufDY7Y3CDjPyvpA==";
    let encrypted = engine::GeneralPurpose::new(&alphabet::STANDARD, config).decode(encrypt).unwrap();
    println!("{:?}", encrypted.len());

    let mut buf = [0u8; 1024];
    let pt = Aes256CbcDec::new(&key_output.into(), &iv_output.into())
        .decrypt_padded_b2b_mut::<Pkcs7>(&encrypted, &mut buf)
        .unwrap();
    println!("{:?}", pt);

}
```
This is the Python code that I want to implement using Rust.
```python
a = "no7AfO7XatdfEGhh1bLIU5wT4U5X2712vyWJbmQAbyK="
key = base64.b64decode(s)
cryptor = AES.new(key,  AES.MODE_CBC, key[:16])
text = "yWgEEgiU97Bd/cX4ezT+Rk/78oJbABb9gr/N73FbBCvgPd3po2JyHYMsSmiyNgEXI+6f2kXxqBdxm/bfTs909UhYvW2PzXzMx4FiDiEAmnogBHNtw7W3kjUZVCDfuU3V1eRRM+QEI+rRXlgMcSKlaLXuEOIKn+AQuD53yXPsXzMdbb+5/Zs8zXddJjN1AtOmI0D8ZJOW6yBjJARk4dFn62Ks/SZai5ec9zg13LZOx8dt1DeI5eF/gqpJZorn5nGhWEX3pR3/XDTwn7u1hdbUeu7Eyu/mmmUQiwlWjVLxIOONHQQRuOSWfy+OePcbvsQSPt4E4Ec6THrW+y5WcWKIEEFSh/GFwC+7ueElNLNErAha6mflewBivoXplC4PRLGB/1uHfV1O1gBxPBtzH2x8X8NlFWptjjGjUSb4jzBj07hmdhPul7bNw0tha7FVibQCUKWqOmiufDY7Y3CDjPyvpA=="
plain_text = cryptor.decrypt(base64.b64decode(text))
```
Thank you for your help, I appreciate any response

**Comment by newpavlov** [comment]
Are you sure that your message uses PKCS7 padding and not something else? I suggest inspecting message decrypted with `NoPadding`, you also will be able to see whether the decrypted text makes sense.

**Comment by baby195lxl** [comment]
@newpavlov Thank you for your reply, but I am certain that this message was padded using PKCS7, as I am using an enterprise [API](https://github.com/sbzhu/weworkapi_python/blob/master/callback/WXBizMsgCrypt3.py). Perhaps implementing decryption in Rust may be a bit challenging for a non-professional enthusiast like me compared to Python, but I still want to do it. Thank you again for your reply.

**Comment by newpavlov** [comment]
By decrypting with `NoPadding` and inspecting the resulting bytes, you could see that your message ends with a bunch of bytes equal to 27, which is bigger than block size of AES. It looks like your message uses a peculiar variant of PKCS7 which goes against the [description](https://www.rfc-editor.org/rfc/rfc5652#section-6.3) in RFC 5652. So your best option is to decrypt with `NoPadding` and remove padding bytes manually (do not forget to validate padding).

**Comment by baby195lxl** [comment]
> FYI in `block-padding v0.3.3` was added support for padding with block size variable at runtime, see the [`RawPadding`](https://docs.rs/block-padding/latest/block_padding/trait.RawPadding.html) trait.

Thank you very much for your response to my question and your contribution to this repository. I hope this project can continue to be maintained and updated, and become a popular crate

**Comment by NaymDev** [comment]
Can I ask what your cargo.toml looks like? I can't figure out what I have to put into my dependencies... to get the same code running you did. Sry if this is a dumb question

**Comment by baby195lxl** [comment]
[package] 
name = "demo" 
version = "0.1.0" 
edition = "2021" 
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 
 
[dependencies] 
base64 = "^0.22" 
sha1 = "0.10.5" 
aes = "0.8.2" 
cbc = "0.1.2" 
rand = "0.8.5"

I don't know if you're asking me, but I hope this can help you.


罗啸林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RustCrypto/block-modes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 上午7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RustCrypto/block-modes] How should I use AES-256-CBC to decrypt? (Issue #37)





 
Can I ask what your cargo.toml looks like? I can't figure out what I have to put into my dependencies... to get the same code running you did. Sry if this is a dumb question
