### ISSUE TITLE
Need to dynamically configure counter limits in CTR stream cipher

### ISSUE THREAD

**Issue by cryptographix** [RustCrypto/block-modes#4]
Currently working on AES-CTR support in Deno .. and W3C WebCrypto requires that the counter increments be limited in "N" RHS bits, such that the LHS is constant during stream operations. This is based on SP800-38 Annex B1.

Tried to hack something based on modified `Ctr128BE` trait but have been unable to configure the increment due to, for example, visibility of `counter` property of `Ctr<..>` or difficulties in passing in as part of `Nonce` due to inicialization route via `NewCipher`/`FromBlockCipher`.

Will happily code this and open a PR, but would like some advice about how to best fit this into current structure and future directions.

**Comment by newpavlov** [comment]
Closing in favor of #1. We probably can add implementation of this mode to `ctr` as a separate type, but it's not clear how counter width should be set.
