### ISSUE TITLE
Ciphertext stealing

### ISSUE THREAD

**Issue by makavity** [RustCrypto/block-modes#41]
Hello!
For `belt-ecb` I need ciphertext stealing. And what is the best way to implement it?
Just make encrypt method and do not process block by block, process always all blocks, or implement block-padding CiphertextStealing, which accept 3*BlockSize and pad only last block?

**Comment by newpavlov** [comment]
I think we need to implement a generic CTS crate, then you would define `belt-ecb` as `Cts<BeltBlock>` and `belt-cbc` as `Cts<cbc::En(De)cryptor<BeltBlock>>`.

**Comment by newpavlov** [comment]
Going to close this issue in favor of #1
