### ISSUE TITLE
Intermediate IV exposing for save/restore APIs

### ISSUE THREAD

**Issue by zugzwang** [RustCrypto/block-modes#5]
Hello folks, would you accept a PR similar to [block-ciphers/pull/227](https://github.com/RustCrypto/block-ciphers/pull/227) as suggested by @newpavlov, allowing to serialize ciphers and continue operation later? Note that even without the exposure, the cryptor can recover the internal IV state at any moment, but this would require additional caching (one full ciphertext block for CFB, and one ciphertext block + one plaintext block + one xor for OFB). Perhaps we could implement the same `IvState` trait.

Regards

cc. @jethrogb

**Comment by cfal** [comment]
> Also note that neither cfb, nor cipher crates include built-in buffering for async stream ciphers. We only provide [consuming byte-level methods](https://docs.rs/cipher/latest/cipher/trait.AsyncStreamCipher.html#method.encrypt), so you may have to implement your own block buffering.

did this used to be supported? `AsyncStreamCipher` took an `&mut self` which allowed it to be used in a streaming manner.. is there a replacement for this or another issue relating to this change?

**Comment by newpavlov** [comment]
@cfal 
Yes, it was. But I think that for most cases the current non-buffering approach is sufficient. It's still possible to build a buffering wrapper around the `AsyncStreamCipher` trait, but currently it's not included into `cipher`. If you need such wrapper, please open an issue in the [traits repository](https://github.com/RustCrypto/traits).

**Comment by cfal** [comment]
@newpavlov thank you, will create an issue!
