### ISSUE TITLE
how to do aes encryption/decryption with ctr model?

### ISSUE THREAD

**Issue by l-7-l** [RustCrypto/block-modes#53]
#### The following code implements AES encryption and decryption using [crypto-js](https://www.npmjs.com/package/crypto-js), but I don't know how to implement it in Rust.
> Sorry for my English

```javascript

function parseKey(aesKey) {
  return {
    iv: CryptoJS.enc.Hex.parse(padEnd('', 32, '0')),
    key: CryptoJS.enc.Base64.parse(aesKey),
  };
}


function aesEncrypt(data, aesKey) {
  const {
    iv,
    key,
  } = parseKey(aesKey);
  const cipherText = CryptoJS.AES.encrypt(JSON.stringify(data), key, {
    iv,
  }).toString();

  return cipherText;
}

// 解密
function aesDecrypt(data, aesKey) {
  const {
    iv,
    key,
  } = parseKey(aesKey);
  const bytes = CryptoJS.AES.decrypt(data, key, {
    iv,
  });
  const decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));

  return decryptedData;
}
```
[stackoverflow link](https://stackoverflow.com/questions/77486071/how-to-do-aes-encryption-and-decryption-in-rust-using-aes-and-ctr-like-crypto-js)

**Comment by newpavlov** [comment]
The `ctr` crate [docs](https://docs.rs/ctr) should be a good starting point. For decoding Base64 you can use the [`base64ct`](https://docs.rs/base64ct) crate.

For further help I recommend asking on the [URLO](https://users.rust-lang.org) forum.
